spring.application.name=agendamento


#Criando conexão com o banco
spring.datasource.url = jdbc:h2:file:./data/agendamentos
spring.datasource.driverClassName = org.h2.Driver
spring.jpa.database-platform = org.hibernate.dialect.H2Dialect

#Usuário e senha do banco de dados
spring.datasource.username = teste
spring.datasource.password = 1234

#Propriedades do console h2
#Acessar o endpoint http://localhost:8080/h2
spring.h2.console.enabled = true
spring.h2.console.path = /h2

#Pedindo o acesso para manipulação da camada DDL
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create


spring.flyway.enabled=false

google.sheets.spreadsheet-id=1n4bofi6rv_2Ob15P7Rxdng7V6aMYHxG9cHph4mbRpBU

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=silvajonathan234@gmail.com
spring.mail.password=kztaekvdrmpymddc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true